spring:
  application:
    name: implementation-of-apachekafka
  #kafka:
   # producer:
      #bootstrap-servers: localhost:9092
      #key-serializer: org.apache.kafka.common.serialization.StringSerializer
      #value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
server:
  port: 9191

