spring:
  application:
    name: 1-Microservice-design-service-registry-knowns-as-Eureka-Server
# server:
 #  port: 8761 # this is default port for eureka server

server:
  port: 9090

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://localhost:9090/eureka/
