spring:
  application:
    name: WELCOME-API
server:
  port: 1111
  
eureka:
  client:
    service-url:
      defaultZone: ${DISCOVERY_URL:http://localhost:9090/eureka}

# if eureka server is running on different machine then give http://<ip-address>:9090/eureka in our case eureka server and client both are running on same machine so we can give http://localhost:9090/eureka.
