spring:
  application:
    name: kafka-schema-registry-with-avro

  kafka:
    bootstrap-servers: "127.0.0.1:9092"
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: io.confluent.kafka.serializers.KafkaAvroSerializer
      properties:
        schema.registry.url: http://127.0.0.1:8081
    consumer:
      group-id: avro-topic-consumer-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: io.confluent.kafka.serializers.KafkaAvroDeserializer
      properties:
        schema.registry.url: http://127.0.0.1:8081
        specific.avro.reader: "true"

# topic.name used by KafkaConfig, KafkaAvroProducer, KafkaAvroConsumer (@Value("${topic.name}"))
topic:
  name: avro-topic-creation

server:
  port: 9095


